### PR TITLE
Downloader

### PR DESCRIPTION
**Pull request by aardila**

### CODE REVIEW

**Comment by aardila** [comment]
So sorry, was trying to merge into my own master branch... :see_no_evil: not enough coffee today...

**Comment by johnjohndoe** [comment]
What's wrong about offering a pull request to this open source project?

**Comment by aardila** [comment]
@johnjohndoe nothing at all! I just submitted the pull request by mistake, and seeing as I didn't include any relevant or meaningful information, I closed it in an attempt to correct my mistake. That said, if having this dockerized is of interest, then by all means let me know.

PS: Sorry, I'm rather new at contributing to open source projects. Thanks for your patience & understanding! :blush:

**Comment by johnjohndoe** [comment]
@aardila My warmest welcome to open source contributions than! :rocket: 
I will however leave the decision whether a Docker setup should be part of the project to @dirkschumacher who started this API.

**Comment by dirkschumacher** [comment]
👍 I don't have any plans with this peace of software as I don't use it actively. So I am a bit indifferent. If Docker can be added in addition then, happy to accept a PR :)

**Pull request closed without merging**
